### ISSUE TITLE
No subject alternative DNS name matching etcd found

### ISSUE THREAD

**Issue by ae6rt** [IBM/etcd-java#32] opened 2020-06-17 02:15 UTC
## etcd-java version

0.0.14

## Expected result

When I connect to a multi-node cluster whose hostnames appear as Subject Alternative Names in the cluster certs, the etcd-java client should honor the Subject Alternative Names during hostname validation after TLS setup.

## Actual result

The etcd-java client ultimately fails, warning that no subject alternative name `etcd` is found:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at com.ibm.etcd.client.GrpcClient.waitFor(GrpcClient.java:748)
	at com.ibm.etcd.client.FluentRequest$AbstractFluentRequest.sync(FluentRequest.java:103)
	at com.xoom.inf.AppTest.connectTest(AppTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1728)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:770)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1043)
	at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:934)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1392)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching etcd found.
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:214)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:96)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:459)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:439)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:286)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
	at io.netty.handler.ssl.OpenSslTlsv13X509ExtendedTrustManager.checkServerTrusted(OpenSslTlsv13X509ExtendedTrustManager.java:221)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:248)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:699)
	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:589)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1172)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1289)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:199)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1329)
	... 21 more

```

Reproducer code:

```
public class AppTest {
    @Test
    public void connectTest() throws Exception {
        List<String> hosts = new ArrayList<String>();
        hosts.add("config-etcd01:2379");
        hosts.add("config-etcd02:2379");
        hosts.add("config-etcd03:2379");
        hosts.add("config-etcd04:2379");
        hosts.add("config-etcd05:2379");
        try {
            final EtcdClient client = EtcdClient.forEndpoints(hosts)
                                                .withCredentials("hello", "world")
                                                .withTlsConfig(new Consumer<SslContextBuilder>() {
                                                    @Override
                                                    public void accept(final SslContextBuilder sslContextBuilder) {
                                                    }
                                                })
                                                .build();
            KvClient kvClient = client.getKvClient();
            PutResponse result = kvClient.put(ByteString.copyFromUtf8("key"), ByteString.copyFromUtf8("value")).sync();
            final RangeResponse sync = kvClient.get(ByteString.copyFromUtf8("key")).asPrefix().sync();
            final KeyValue kvs = sync.getKvs(0);
            System.out.println(kvs.getValue());
        } catch (SSLException e) {
            e.printStackTrace();
        }
    }
}
```

Oddly enough, when I reduce the cluster host list from 5 members to 1 (e.g. `config-etcd01`), TLS setup succeeds and the test code works as expected.

These are the baseline cert Subject Alternative Names (SAN) present in each cluster node cert

```
DNS:config-etcd01, DNS:config-etcd02, DNS:config-etcd03, DNS:config-etcd04, DNS:config-etcd05
```
The node certificates do have a populated X500 DN Common Name (CN) field equal to `etcd`, but that does not remove the exception.  

If I add `etcd` as an explicit SAN, the test code succeeds with a 5-member host list.

I feel like I'm missing something terribly obvious, but ask I must:  what am I doing wrong?

Thanks.

**Comment by njhill** [comment] 2020-06-17 17:25
@ae6rt thanks for the report. I don't think you are missing anything, this is a current deficiency. Setting the CN doesn't work because Java is strict about the https spec (see [RFC2818](http://tools.ietf.org/html/rfc2818#section-3.1)) and won't use the CN if any SANs are present. So I think your _current_ options are to have the CN be `etcd` with no SANs, or include `etcd` as a SAN as you already verified works. But I know neither of these are very satisfactory.

The reason things are like this is due to a limitation of earlier versions of grpc-java, which I only just discovered has since been fixed in https://github.com/grpc/grpc-java/pull/6126, so I can hopefully now fix the behaviour properly in this client. Then you can just use your cert with the real SANs and not reference `etcd` at all. Note that the only reason that this is considered secure is that the list of endpoints is statically configured.

There will be a new release of this client soon and I'll aim to have that improvement incorporated.

P.S. I notice in your reproducer that you're calling `withTlsConfig()` with a no-op `Consumer`. Is this just because you removed some code from there? It should not be necessary to include this otherwise, TLS is the default unless `withPlainText` is used.

**Comment by ae6rt** [comment] 2020-06-17 19:29
@njhill Thank you for the thorough response.  I'll click `Watch / Releases`, and gratefully await the next release.

As for `withTlsConfig()`, I naively assumed the client needed that hint, but glad to hear it doesn't.

Many thanks.

**Comment by njhill** [comment] 2020-06-18 21:56
@ae6rt any chance you could try out branch https://github.com/IBM/etcd-java/tree/tls-endpoints-fix to verify it works for you?

**Comment by ae6rt** [comment] 2020-06-18 23:44
Alas it does not.  

Here's what I did:

## Built and installed your branch 

```
$ git branch
  master
* tls-endpoints-fix
```

```
$ mvn clean install -DskipTests
```
```
...
[INFO] --- maven-install-plugin:2.4:install (default-install) @ etcd-java ---
[INFO] Installing /Users/mpetrovic/Projects/etcd-java/target/etcd-java-0.0.15-SNAPSHOT.jar to /Users/mpetrovic/.m2/repository/com/ibm/etcd/etcd-java/0.0.15-SNAPSHOT/etcd-java-0.0.15-SNAPSHOT.jar
[INFO] Installing /Users/mpetrovic/Projects/etcd-java/pom.xml to /Users/mpetrovic/.m2/repository/com/ibm/etcd/etcd-java/0.0.15-SNAPSHOT/etcd-java-0.0.15-SNAPSHOT.pom
[INFO] Installing /Users/mpetrovic/Projects/etcd-java/target/etcd-java-0.0.15-SNAPSHOT-javadoc.jar to /Users/mpetrovic/.m2/repository/com/ibm/etcd/etcd-java/0.0.15-SNAPSHOT/etcd-java-0.0.15-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.669 s
[INFO] Finished at: 2020-06-18T16:40:15-07:00
[INFO] ------------------------------------------------------------------------
```

## Updated my app POM

Make sure I'm building with your snapshot artifact

```
mvn dependency:tree
...
+- com.ibm.etcd:etcd-java:jar:0.0.15-SNAPSHOT:compile
...
```

then run my code

```
mvn -q clean test
```

which emits more or less the same error

```
Running com.xoom.inf.AppTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.594 sec <<< FAILURE!
connectTest(com.xoom.inf.AppTest)  Time elapsed: 1.543 sec  <<< ERROR!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at com.ibm.etcd.client.GrpcClient.waitFor(GrpcClient.java:748)
	at com.ibm.etcd.client.FluentRequest$AbstractFluentRequest.sync(FluentRequest.java:103)
	at com.xoom.inf.AppTest.connectTest(AppTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1728)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:770)
	at java.base/javax.net.ssl.SSLEngine.wrap(SSLEngine.java:519)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1043)
	at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:934)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1392)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching etcd found.
	at java.base/sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:207)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:98)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:459)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:434)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:291)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:248)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:699)
	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:589)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1172)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1289)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:199)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1329)
	... 21 more

```

I'm in the Kubernetes etcd channel as `ae6rt` if you want to chat realtime.

**Comment by ae6rt** [comment] 2020-06-19 12:59
Here's a container that (should) mimic the one on which this issue was originally based.  It uses a throwaway CA, and not the one I use internally at work.  It has the same SANs as my work-container, so it should be a drop in replacement.  

https://github.com/ae6rt/etcd-public-container

```
make etcd
```

will build the image and run it.  At which point my sample Java code above would be run against it.

hth

**Comment by njhill** [comment] 2020-06-19 16:42
Thanks very much for this @ae6rt. My original fix was incorrect, should now be resolved. I was able to verify it works with your test container. Do you think you could try it out again to be sure?

**Comment by ae6rt** [comment] 2020-06-19 19:53
@njhill  You fixed it!

Thank you so much for addressing this so quickly.  Hugely appreciated.

Mark

**Closed** 2020-06-19 22:10 UTC

**Comment by njhill** [comment] 2020-06-21 20:40
@ae6rt version 0.0.15 is now released which includes this fix.
